[project]
name = "apache-spark-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nbclient>=0.10.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pyspark>=4.0.1",
]
